name: GitHub to Slack Notification

on:
  push:
    branches:
      - main

jobs:
  notify-slack:
    runs-on: ubuntu-latest

    steps:
      - name: Send Slack Notification
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{
            "text":"🚀 New code pushed to GitHub repository: ${{ github.repository }} by ${{ github.actor }}"
          }' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
